name         'conductas-opendj'
version      '0.0.2'
source       'git@github.com:ConductAS/puppet-opendj.git'
author       'Eivind Mikkelsen <eivindm@conduct.no>'
license      'Simplified BSD License'
summary      'OpenDJ configuration module'
description  'Module for configuration of ForgeRock OpenDJ'
project_page 'https://github.com/ConductAS/puppet-opendj'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
