name        'conduct-opendj'
version     '0.0.2'
author      'Eivind Mikkelsen <eivindm@conduct.no>'
license     'Simplified BSD License'
summary     'OpenDJ configuration module'
description 'Module for configuration of ForgeRock OpenDJ'
